version: '3'

services:
  etcd:
    image: docker.io/bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
    - etcd_data:/bitnami/etcd
    ports:
    - 2379:2379

  planet_generated:
    image: quay.io/apibara/sink-postgres:0.4.10
    depends_on:
    - etcd
    restart: always
    command:
    - run
    -  --allow-env=/data/.env 
    - /data/src/planetGenerated.ts
    volumes:
    - ./:/data/
    - .certificates/prod-ca-2021.pem:/certs/prod-ca-2021.pem
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: planet-generated
      AUTH_TOKEN: ${AUTH_TOKEN}

  resources_spent:
    image: quay.io/apibara/sink-postgres:0.4.10
    depends_on:
    - etcd
    restart: always
    command:
    - run
    -  --allow-env=/data/.env 
    - /data/src/resourcesSpent.ts
    volumes:
    - ./:/data/
    - .certificates/prod-ca-2021.pem:/certs/prod-ca-2021.pem
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: resources-spent
      AUTH_TOKEN: ${AUTH_TOKEN}

  upgrades_levels:
    image: quay.io/apibara/sink-postgres:0.4.10
    depends_on:
    - etcd
    restart: always
    command:
    - run
    -  --allow-env=/data/.env 
    - /data/src/upgradesLevels.ts
    volumes:
    - ./:/data/
    - .certificates/prod-ca-2021.pem:/certs/prod-ca-2021.pem
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: upgrades-levels
      AUTH_TOKEN: ${AUTH_TOKEN}

  battle_reports:
    image: quay.io/apibara/sink-postgres:0.4.10
    depends_on:
    - etcd
    restart: always
    command:
    - run
    -  --allow-env=/data/.env 
    - /data/src/battleReport.ts
    volumes:
    - ./:/data/
    - .certificates/prod-ca-2021.pem:/certs/prod-ca-2021.pem
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: battle-reports
      AUTH_TOKEN: ${AUTH_TOKEN}


volumes:
  etcd_data:
