on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV_CONTENTS: ${{ secrets.ENV_CONTENTS }}
      PEM_CERTIFICATE: ${{ secrets.PEM_CERTIFICATE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e

            # Navigate to the project directory
            cd /opt/indexer/nogame-indexer

            # Update the repository
            git fetch --all
            git reset --hard origin/main

            # Create or update .env file
            echo "$ENV_CONTENTS" > .env

            # Create or update SSL certificate
            mkdir -p .certificates
            echo "$PEM_CERTIFICATE" > .certificates/prod-ca-2021.pem

            # Source the .env file
            source .env

            # Restart or start the systemd service
            if systemctl --quiet is-active indexer.service; then
              sudo systemctl restart indexer.service
            else
              sudo systemctl start indexer.service
              sudo systemctl enable indexer.service
