on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e

            # Navigate to the project directory
            cd /opt/indexer/nogame-indexer

            # Update the repository
            git fetch --all
            git reset --hard origin/main

            # Create or update .env file
            echo `${{ secrets.ENV_CONTENTS }}` > .env

            # Create or update SSL certificate
            mkdir -p .certificates
            echo `${{ secrets.PEM_CERTIFICATE }}` > .certificates/prod-ca-2021.pem
