on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Pull latest changes
            cd /opt/indexer/nogame-indexer  
            git fetch origin main
            git reset --hard origin/main
            git pull origin main

            # Update .env file
            echo '${{ secrets.ENV_CONTENTS }}' > .env

            # Update SSL certificate
            mkdir -p ./.certificates
            echo '${{ secrets.PEM_CERTIFICATE }}' > .certificates/prod-ca-2021.pem

            # Run Docker Compose
            source .env
            docker-compose up -d

            # Setup or restart systemd service
            if systemctl --quiet is-active indexer.service; then
              sudo systemctl restart indexer.service
            else
              sudo systemctl start indexer.service
              sudo systemctl enable indexer.service
